language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gossdoss/travis-react-001 -f Dockerfile.dev .
script:
  - docker run -e CI=true gossdoss/travis-react-001 npm run test